### ISSUE TITLE
New dropped inputs or cursor freeze and sometimes crash immediately after exiting Livestream or VOD

### ISSUE THREAD

**Issue by fireworksordie** [fgl27/SmartTwitchTV#14]
**Describe the bug**
Major lag or often a full crash to home screen after exiting a user VOD and trying to navigate. Similar but lesser version of the problem with exiting a livestream.

**To Reproduce**
1. Go to play a user's VOD from their Videos section (in tonight's particular example, @kylebosman's Avengers stream from August 7th)
2. Exit back to the screen with all of the VODs (on my remote, hit back twice). 
3. Try to navigate the selection box/cursor any direction. 

**Expected behavior**
Before this issue started occurring, navigation would be smooth and instant and I could immediately jump into another VOD or head all the way left to the menu. 

Now navigation (but not VOD preview playback, though disabling that doesn't fix the issue) freezes for 5 to 8 seconds, then either crashes to home screen or drops most inputs but eventually the navigation starts working again.

**Screenshots**
N/A, but I can provide a video of the issue if that would help. 
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield TV
 - Os version: Latest (8.0.2)

**Additional context**
Tried clearing data just in case it was a weird cache thing, but no luck. Issue seems to have started happening within the last week. This sluggishness and lag issue also seems to be affecting exiting from Livestreams then navigating as well, but lags only for a few seconds and doesn't seem to have crashed like with VODs yet for me. It's basically like the app is stuck completely ignoring inputs for a good 3 to 5 seconds with Livestreams and more seconds from VODs with the high chance of crashing.

**Comment by fgl27** [comment]
A thing that I know, that can cause input lag like this is if you have enable a accessibility service, do you?

And is most noticeable when exiting a playback.

But maybe is something else, some user reported on the past odd lag and slowdowns that was caused by random Android issues that are resolved by simply power the device off (off the wall), device is on for days and days something odd on the background happens and random issues start.

On the case of none of the above help... is needed a bug report.

To produce one you need to enable developer options after on the developer options change the log size to 16MB

![Settings_20200814_015914](https://user-images.githubusercontent.com/13755892/90215683-c23efd00-ddd2-11ea-8e08-c5275982e847.png)

This will allow to get a full log as the default log is too short.

When the app crashes you generate a bug report developer options

![Settings_20200814_015922](https://user-images.githubusercontent.com/13755892/90215713-e569ac80-ddd2-11ea-86dc-97babb7b5058.png)

When it finishes you will see this

![FX_20200814_020139](https://user-images.githubusercontent.com/13755892/90215724-f0244180-ddd2-11ea-97ef-55686bae49be.png)

and there will be a notification that allows you to click and share the bug, by default it will send to the email of yours main device google account

![BugReportSender_20200814_020831](https://user-images.githubusercontent.com/13755892/90215794-37123700-ddd3-11ea-85c9-01b0ad27ac62.png)

Once you receive that you can forward that email to fglfgl27@gmail.com or drag it to a new post here...

Please explain the last steps that cause the crash when sharing a bug report.

BTW I never notice a issue like this on my 2017 Shield...

**Comment by fireworksordie** [comment]
Thanks! I do have Accessibility Service on but have ever since using this app back in March and never had any issues up until this past week, so I'm not sure why this issue would have suddenly started happening otherwise - nothing else has changed on my Shield since. I'll report back soon.

**Comment by fgl27** [comment]
Yes that is way I have add a warning on the app

![SmartTV for Twitch_20200814_114654](https://user-images.githubusercontent.com/13755892/90277763-89d40900-de3c-11ea-8739-c8145ef1ae88.png)

I will pass this to google see what they have to say, I manage to find a way that always causes a crash and this is a major flow on they system.

I'll update this when I have some news.

**Comment by fireworksordie** [comment]
Disabling the only app (ButtonMapper) that was using Accessibility fixes it, but I'm still not sure I understand why the lag/crashes would have only just started happening this week? I've been using ButtonMapper with Accessibility on for at least a couple months now. Would it still be helpful to grab a log since it's clearly affected by a recent app update?

**Comment by fgl27** [comment]
No need for logs see https://bugs.chromium.org/p/chromium/issues/detail?id=1116537

This has happen before same app causes the issue ButtonMapper, that was a long time ago over a year, and has happen to multiple devices/apps...

I don't know why it comes and goes, only affect one app, when there is not just twitch apps, but general apps like youtube that do the same thing, open a video exit the video no lag no issue..

Some device don't have issue some do... read the [link](https://www.xda-developers.com/working-as-intended-an-exploration-into-androids-accessibility-lag/) of the warning there is some extra info there...

Android is just odd some times.

Thanks for the information...

When update come from that bug on chromium site happens I update this.

**Comment by fireworksordie** [comment]
Ah wow, not surprising but that's a better bug report than I ever would have been able to file. Really appreciate it. I'll keep an eye on this but luckily the Button Mapper thing was only to disable the annoying Netflix button on the Shield remote, not a huge hassle if I turn off Button Mapper. Wish there was a better way to disable or re-map that!

**Comment by fgl27** [comment]
commit https://github.com/fgl27/SmartTwitchTV/commit/af74771217c0b1e309595d069e5315f5a7dbf413 mitigate the problem, isn't a full fix slows downs are noticeable but that will prevent 90% of it and prevent crashes.

Change was pushed to the app, close the app and reopen it so it updatess.

**Comment by fgl27** [comment]
On august 6 I made this change
https://github.com/fgl27/SmartTwitchTV/commit/4d265cb7402ff4d5dc131fa0c4fa3954ccd2a23e

And after that we have severe lag when accessibility services are enabled...

I revert all back here https://github.com/fgl27/SmartTwitchTV/commit/fb30a5b15f52fc20113f687d89223d9f01d899cd

Plus the changes I made before the performance is back to a OK state, but accessibility services will cause some slow down, I hope chromium team can help to improve that.

**Comment by fireworksordie** [comment]
Yep! This seems to have done the trick essentially. Really impressed - thank you. Did some entering livestreams and backing out and while I'm now aware of what's it's like with accessibility off with zero lag, this is a great solution and certainly close enough. Seems like this issue can be closed since this is as close as it will get.

**Comment by fgl27** [comment]
I'll wait some resolution from chromium site, and then I close this.

I notice a difference when accessibility is enable VS when is not, is most noticeable on animations.

Without accessibility services running animations are smooth as expected there is 0 click delay, with accessibility services running I notice a minor delay on key press and as if I'm not running the device at 60 fps, is not close as if I set it to 30 but fells something on between and ins't a smooth animation.

That behavior is on the 2017 Shield.

This probably can't be improve, but maybe the resolution from chromium site can help.

Thanks for the feedback.

**Comment by fgl27** [comment]
no update yet the chromium issue is:

https://bugs.chromium.org/p/chromium/issues/detail?id=1369619#c8
