### ISSUE TITLE
Bitrate difference

### ISSUE THREAD

**Issue by CristianGrecu** [fgl27/SmartTwitchTV#207]
Hello, I am not 100% sure this is a real problem, so I apologise if this is a waste of time. I've recently noticed that the bitrate that the top right stats panel shows is way lower than normal. Streams that used to show 9 Mbps now show 4-5. A lot of streams seem to be at even lower values like 3 Mbps. This doesn't seem to affect IRL streams in the same way. I checked on a PC using Chrome and the bitrates are super high as usual. I'm not sure there is a difference in quality because the displays that I use are so different vs a large TV. 

I am not a software developer so I have no idea if Twitch started messing with some codecs or if anything is wrong to begin with. 

Thank you in advance!!

**Comment by fgl27** [comment]
Is a Twitch bug, they are providing the wrong bitrate for lives

If you go to the VOD of the same Live you can see the proper value

I expect them to fix this but technically they may not, so I will have to come up with a workaround as this messes up the auto playback that is bitrate base as it depends on analysing the internet available bandwidth vs bitrate to determinate what quality to pick.

**Comment by fgl27** [comment]
The above fixes it for now, I will let this open so I can improve in the future

the above was pushed to the app just close and reopen it so the app update it self

**Comment by fgl27** [comment]
if any other related issue is found let me know here

**Comment by CristianGrecu** [comment]
Thank you!

**Comment by RikuXan** [comment]
Just to clarify: the bitrate is still displayed incorrectly, just the choice of quality logic has been fixed, correct?

**Comment by fgl27** [comment]
> Just to clarify: the bitrate is still displayed incorrectly, just the choice of quality logic has been fixed, correct?

the bitrate of affected streams for the source stream is approximated but that isn't incorrect.

**Comment by RikuXan** [comment]
Ah sorry. I had a few streams where the displayed bitrate was still surprisingly low.
But if there is no accurate information given out by Twitch anymore an approximation is all you can do.

**Comment by fgl27** [comment]
For now yes, from the streams that I checked the diff is around 0.5 to 1 Mbps

To check is simple your just open the vod is there live and compare.

For some wild reason the vod values are fine.

also this seems a issue only from a few country's, for example some us stream are affected but eu of the same type resolution fps aren't.

**Comment by CristianGrecu** [comment]
Hello again, it seems that the problem is back, but only for specific channels this time. I've found quite a few examples that show 3.59 Mbps while live, but 8.76 while watching the VOD. I only watch at source quality, but I guess it could affect the people using "auto".

**Comment by fgl27** [comment]
That isn't a problem

As long the source bitrate is bigger then the rest auto playback will just work.

Nothing I can do if all bitrates not just the sorce one are fucked

**Comment by CristianGrecu** [comment]
Oh, I see, I've never used anything lower than source or "auto", so I didn't even think about checking the values. Thank you!
